export const clientesData = [
    {
      id: 1,
      razaoSocial: "Empresa ABC Ltda",
      nomeFantasia: "ABC Comercial",
      cnpj: "12.345.678/0001-90",
      inscricaoEstadual: "123.456.789",
      matriz: "Matriz",
      redeCliente: "Rede 1",
      limiteCredito: 50000,
      tipoContribuinte: "Contribuinte ICMS",
      endereco: "Av. Paulista",
      numero: "1000",
      complemento: "Sala 123",
      bairro: "Bela Vista",
      cep: "01310-100",
      cidade: "São Paulo",
      estado: "SP",
      telefone: "(11) 3456-7890",
      fax: "(11) 3456-7891",
      telefoneAdicional: "(11) 98765-4321",
      email: "contato@abc.com",
      emailFinanceiro: "financeiro@abc.com",
      website: "www.abc.com",
      instagram: "@abccomercial",
      facebook: "facebook.com/abccomercial",
      status: "Ativo",
      classificacaoSV: "A",
      formaPagamento: "Boleto",
      vendedor: "Carlos Silva",
      categoria: "Categoria 1",
      observacoes: "Cliente desde 2020. Excelente histórico de pagamentos.",
      tipo: "empresa",
      classificacoes: ["cliente"]
    },
    {
      id: 2,
      razaoSocial: "Distribuidora XYZ",
      nomeFantasia: "XYZ Distribuição",
      cnpj: "23.456.789/0001-89",
      inscricaoEstadual: "234.567.890",
      matriz: "Matriz",
      redeCliente: "Rede 2",
      limiteCredito: 75000,
      tipoContribuinte: "Contribuinte ICMS",
      endereco: "Rua da Distribuição",
      numero: "500",
      complemento: "Galpão 2",
      bairro: "Centro",
      cep: "20000-000",
      cidade: "Rio de Janeiro",
      estado: "RJ",
      telefone: "(21) 3456-7890",
      fax: "(21) 3456-7891",
      telefoneAdicional: "(21) 98765-4321",
      email: "contato@xyz.com",
      emailFinanceiro: "financeiro@xyz.com",
      website: "www.xyz.com",
      instagram: "@xyzdist",
      facebook: "facebook.com/xyzdist",
      status: "Ativo",
      classificacaoSV: "A",
      formaPagamento: "Boleto",
      vendedor: "Ana Santos",
      categoria: "Categoria 1",
      observacoes: "Distribuidor exclusivo região sudeste",
      tipo: "empresa",
      classificacoes: ["cliente"]
    },
    {
      id: 3,
      razaoSocial: "Comércio Sul Ltda",
      nomeFantasia: "Sul Comércio",
      cnpj: "34.567.890/0001-78",
      inscricaoEstadual: "345.678.901",
      matriz: "Filial",
      redeCliente: "Rede 3",
      limiteCredito: 30000,
      tipoContribuinte: "Contribuinte ICMS",
      endereco: "Av. dos Andradas",
      numero: "1500",
      complemento: "Loja 1",
      bairro: "Centro",
      cep: "90000-000",
      cidade: "Porto Alegre",
      estado: "RS",
      telefone: "(51) 3456-7890",
      fax: "(51) 3456-7891",
      telefoneAdicional: "(51) 98765-4321",
      email: "contato@sulsul.com",
      emailFinanceiro: "financeiro@sulsul.com",
      website: "www.sulsul.com",
      instagram: "@sulcomercio",
      facebook: "facebook.com/sulcomercio",
      status: "Inativo",
      classificacaoSV: "B",
      formaPagamento: "Boleto",
      vendedor: "Roberto Lima",
      categoria: "Categoria 2",
      observacoes: "Atendimento região sul",
      tipo: "empresa",
      classificacoes: ["cliente"]
    }
  ];